COMPANY_ALIASES: dict[str, str] = {
    'GOOGLE': 'GOOGL',
    'MICROSOFT': 'MSFT',
    'APPLE': 'AAPL',
    'TESLA': 'TSLA',
    'AMAZON': 'AMZN',
    'NETFLIX': 'NFLX',
    'FACEBOOK': 'META',
    'NVIDIA': 'NVDA',
    'AMD': 'AMD',
    'INFOSYS': 'INFY.NS',
    'TATA STEEL': 'TATASTEEL.NS',
    'TATA MOTORS': 'TATAMOTORS.NS',
    'RELIANCE': 'RELIANCE.NS',
    'WIPRO': 'WIPRO.NS',
    'HDFC': 'HDFCBANK.NS',
    'HDFC BANK': 'HDFCBANK.NS',
    'ICICI BANK': 'ICICIBANK.NS',
    'SBI': 'SBIN.NS',
    'STATE BANK OF INDIA': 'SBIN.NS',
    'BAJAJ FINANCE': 'BAJFINANCE.NS',
    'ASIAN PAINTS': 'ASIANPAINT.NS',
    'MARUTI': 'MARUTI.NS',
    'TITAN': 'TITAN.NS',
    'SUN PHARMA': 'SUNPHARMA.NS',
    'ULTRATECH': 'ULTRACEMCO.NS',
    'POWER GRID': 'POWERGRID.NS',
    'TCS': 'TCS.NS',
    'ITC': 'ITC.NS',
    'PW': 'PWL.NS',
    'PHYSICSWALLAH': 'PWL.NS',
    'PHYSICS WALLAH': 'PWL.NS',
}

DEFAULT_PERIOD: str = "1y"
CACHE_TTL: int = 300

INDICATOR_WINDOWS: dict[str, int] = {
    'SMA_FAST': 20,
    'SMA_SLOW': 50,
    'RSI': 14,
    'MACD_FAST': 12,
    'MACD_SLOW': 26,
    'MACD_SIGNAL': 9,
    'BB': 20,
    'ATR': 14,
}

PREDICTION_DAYS: int = 10
BACKTEST_DAYS: int = 10
POLL_INTERVAL_MS: int = 10_000

MAX_TICKER_LENGTH: int = 20
ALLOWED_TICKER_CHARS: str = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789. "
